project:
  type: website

website:
  title: "posit::conf(2023)"
  page-navigation: true
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: workshop.qmd
        text: Workshop
      - href: talks.qmd
        text: Talks
      - sidebar:misc
  sidebar: 
    - id: misc
      title: "Misc"
      contents:
        - auto: misc
        - bibliography.qmd
   
bibliography: references.bib

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 4
    toc-location: left
    from: markdown+emoji
    citation-location: margin