---
title: "Day 1 - Workshop"
format: html
---

## Workshop Abstract

[:link: Introduction to Quarto with R & RStudio](https://posit-conf-2023.github.io/workshops/workshops/quarto-r-docs/)

> This workshop will prepare you to author a rich array of documents in Quarto, the next generation of R Markdown. Quarto is an open-source scientific and technical publishing system that offers multilingual programming language support to create dynamic and static documents, books, presentations, blogs, and other online resources.
>
>The focus for this workshop will be on single documents. You will learn to create static documents, to add interactivity to them with Shiny and htmlwidgets, or steer them in the direction of sophisticated scientific documents. In the afternoon you’ll take the same authoring approaches to create slide presentations in various formats such as reveal.js, beamer, and pptx.

## Workshop Notes

Resources:

- [Workshop website and slides](https://posit-conf-2023.github.io/quarto-r/)
- [Quarto official docs](https://quarto.org)

